export default [
    {
      id: 1,
      postedOn: new Date(),
      title: "Frontend Developer",
      type: "Full time",
      location: "Work-from-home",
      companyName: "Google",
      companyUrl: "Google.com",
      skills: ["Javascript", "React.js", "Node.js"],
      link: "https://google.com/careers",
    },
    {
      id: 2,
      postedOn: new Date(),
      title: "Backend Developer",
      type: "Part time",
      location: "Office",
      companyName: "TCS",
      companyUrl: "tcs.com",
      skills: ["Angular", "Node.js"],
      link: "https://www.tcs.com/careers?country=IN&lang=EN",
    },
    {
      id: 3,
      postedOn: new Date(),
      title: "Full Stack Developer",
      type: "Internship",
      location: "Hybrid",
      companyName: "Facebook",
      companyUrl: "https://facebook.com",
      skills: ["flutter","React.js","Node.js"],
      link: "https://facebook.com/careers",
    },
    {
      id: 4,
      postedOn: new Date(),
      title: "Web Designer",
      type: "Part Time",
      location: "Office",
      companyName: "Masai School",
      companyUrl: "https://masaischool.com",
      skills: ["Angular","React.js","vue.js"],
      link: "https://masaischool.com/masai-x",
    },
  ];